# .github/workflows/ci-cd.yml
name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Prepare data
      run: |
        source env/bin/activate
        python scripts/prepare_data.py

    - name: Train model
      run: |
        source env/bin/activate
        python scripts/train_model.py

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/yshokrollahi/mlops-demo:latest .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/yshokrollahi/mlops-demo:latest

    - name: Deploy Docker container
      run: |
        docker run -d -p 5000:5000 ghcr.io/yshokrollahi/mlops-demo:latest
